---
- name: Get AD Users and create HTML report
  hosts: windows
  gather_facts: no
  tasks:

    - name: Get AD user accounts with groups and lock status
      win_shell: |
        Import-Module ActiveDirectory
        Get-ADUser -Filter * -Property DisplayName, EmailAddress, SamAccountName, MemberOf, LockedOut |
        Select-Object DisplayName, EmailAddress, SamAccountName, @{Name="Groups";Expression={(Get-ADUser -Identity $_.SamAccountName -Property MemberOf | Select-Object -ExpandProperty MemberOf | Get-ADGroup | Select-Object -ExpandProperty Name) -join ", "}}, LockedOut |
        ConvertTo-Json
      register: ad_users

    - name: Create HTML file from template
      template:
        src: templates/users_template.html.j2
        dest: /user_report.html
      vars:
        users: "{{ ad_users.stdout | from_json }}"
